version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: twitterclone
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    ports:
      - "35432:35432"
  web:
    image: gajo/twitter-sql-ts
    depends_on: 
      - db
    ports:
      - "3000:3000"